services:
  db:
    image: mariadb:lts-ubi
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: testpassword
    volumes:
      - dbvol:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mariadb-admin ping -h 127.0.0.1 -u root -p$$MARIADB_ROOT_PASSWORD'
      timeout: 1s
      retries: 30

  migrator:
    image: leophys/migrator
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DB_USER: root
      DB_PASS: testpassword
      DB_HOST: db
      TESTDB_USER: testuser
      TESTDB_PASSWORD: userpassword
    volumes:
      - ./testmigrations:/migrations
      - ./testtemplates:/templates
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbvol: {}
