services:
  db:
    image: mariadb:lts-ubi
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: testpassword
    volumes:
      - dbvol:/var/lib/mysql

  migrator:
    image: leophys/migrator
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DB_USER: root
      DB_PASS: testpassword
      DB_HOST: db
      TESTDB_USER: testuser
      TESTDB_PASSWORD: userpassword
    volumes:
      - ./testmigrations:/migrations
      - ./testtemplates:/templates
    depends_on:
      - db

volumes:
  dbvol: {}
